In [1]:
import numpy as np
from sklearn.neural_network import MLPClassifier

In [2]:
# load initial dataset
base_dataset = np.loadtxt('base_dataset.csv', delimiter=',')

In [3]:
print("A, B, C, D")
print(base_dataset)

A, B, C, D
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]


In [4]:
# construct additional dataset by repeating base_dataset 9 times
add_set = np.tile(base_dataset, (9, 1))

In [5]:
# replace A,B,C zeros with random values in interval 0,0.4
np.place(add_set[:,:-1], add_set[:,:-1]==0, np.random.uniform(0,0.4,(add_set[:,:-1]==0).sum()))

In [6]:
# replace A,B,C ones with random values in interval 0.6,1.2
np.place(add_set[:,:-1], add_set[:,:-1]==1, np.random.uniform(0.6,1.2,(add_set[:,:-1]==1).sum()))

In [7]:
# create train dataset concatenating initial base_dataset and generated add_set
dataset = np.concatenate((base_dataset,add_set), axis=0)

In [8]:
print("size:\n", dataset.shape)
print("dataset:\n", dataset[:16,:])

size:
 (80, 4)
dataset:
 [[0.         0.         0.         1.        ]
 [0.         0.         1.         0.        ]
 [0.         1.         0.         1.        ]
 [0.         1.         1.         0.        ]
 [1.         0.         0.         1.        ]
 [1.         0.         1.         0.        ]
 [1.         1.         0.         1.        ]
 [1.         1.         1.         0.        ]
 [0.04234072 0.33291513 0.23717993 1.        ]
 [0.25148961 0.26871074 0.72122035 0.        ]
 [0.25644835 0.82398849 0.35826793 1.        ]
 [0.20039741 0.84802037 0.69756657 0.        ]
 [0.93715877 0.35092931 0.17326311 1.        ]
 [0.86079911 0.06300042 0.95462675 0.        ]
 [1.07015972 1.10436778 0.36347492 1.        ]
 [0.74234275 1.16401122 1.19850165 0.        ]]


In [9]:
# input and output for classifier
X = dataset[:,:-1]
y = dataset[:,-1]

In [10]:
# initializing the MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)

In [11]:
# fitting data to the network
clf.fit(X, y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

In [12]:
# generate data for predict
samples = np.concatenate((np.random.uniform(0.,0.4, 15),np.random.uniform(0.6,1.2, 15)))
np.random.shuffle(samples)
samples = samples.reshape((10,3))

In [13]:
print(samples)

[[0.15876662 0.72381493 1.06125891]
 [0.86059849 0.12101969 0.0488735 ]
 [0.95368002 1.02178768 0.84519577]
 [0.15611362 0.25710789 1.10219139]
 [0.26157839 0.63727799 0.29401909]
 [0.34303027 0.80268896 0.89055014]
 [0.88069916 0.13856363 0.91236076]
 [0.83684064 0.92702365 0.01050989]
 [0.13583116 0.21415074 0.33190842]
 [0.38113047 0.1032304  0.69865941]]


In [14]:
clf.predict(samples)

array([0., 1., 0., 0., 1., 0., 0., 1., 1., 0.])