In [1]:
import numpy as np

In [2]:
# Basic Unary ufuncs list excluding sqrt
METHODS_LIST = ['abs','fabs','square','exp','log','log10','log2','log1p','sign','ceil','floor','rint','modf'
             ,'isnan','isfinite','isinf','cos','cosh','sin','sinh','tan','tanh','arccos','arccosh','arcsin'
             ,'arcsinh','arctan','arctanh','logical_not']

In [3]:
class B():
    @staticmethod
    def mask(input_array, index):
    # Create bool array for parameter -where of ufunc.
        w = np.zeros(input_array.shape, dtype=bool)
        w[index] = 1
        return w
    
    def sqrt(self, input_array, index=None):
    # At locations -where the condition is True, the -out array will be set to the ufunc result.
    # Where the condition is False, the -out array will be set to zero.
        return np.sqrt(np.abs(input_array), where=self.mask(input_array, index), out=np.zeros(input_array.shape))
    
    # convert the original 2D array into a 3D one by copying
    def repeat3d(self, input_array, repeats=2):
        return np.repeat(input_array[:, :, np.newaxis], repeats, axis=2)

In [4]:
# Add ufunc methods to class B
for i in METHODS_LIST:
    # define function
    exec(f"def {i}(self, input_array, index=None):\
         return np.{i}(input_array, where=self.mask(input_array, index), out=np.zeros(input_array.shape))")
    
    #  set attribute to class B
    exec(f"setattr(B, '{i}', classmethod({i}))")
    
    # delete function
    exec(f"del {i}")

In [5]:
obj = B()

In [6]:
a = np.arange(9).reshape(3,3)**2
print(a)

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [7]:
print(obj.sqrt(a,[0,2]))

[[0. 1. 2.]
 [0. 0. 0.]
 [6. 7. 8.]]


In [8]:
np.random.seed(42)
b = np.random.randn(16).reshape(4,4)
print(b)

[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]]


In [9]:
print(obj.fabs(b,[2,3]))

[[0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.46947439 0.54256004 0.46341769 0.46572975]
 [0.24196227 1.91328024 1.72491783 0.56228753]]


In [10]:
np.random.seed(42)
c = np.random.normal(size=(5, 5))
print(c)

[[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [-0.23413696  1.57921282  0.76743473 -0.46947439  0.54256004]
 [-0.46341769 -0.46572975  0.24196227 -1.91328024 -1.72491783]
 [-0.56228753 -1.01283112  0.31424733 -0.90802408 -1.4123037 ]
 [ 1.46564877 -0.2257763   0.0675282  -1.42474819 -0.54438272]]


In [11]:
obj.floor(c,[0,2,4])

array([[ 0., -1.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [-1., -1.,  0., -2., -2.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 1., -1.,  0., -2., -1.]])

In [12]:
d = np.arange(9).reshape(3,3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
d3d = obj.repeat3d(d,2)

In [14]:
print(d3d[:,:,0])
print(d3d[:,:,1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
