In [1]:
import numpy as np
from sklearn.neural_network import MLPClassifier

In [2]:
# given true table A, B, C, D=F(A,B,C)
# true_table = np.loadtxt('base_dataset.csv', delimiter=',')
true_table =  np.array([[0, 0, 0, 1],
                          [0, 0, 1, 0],
                          [0, 1, 0, 1],
                          [0, 1, 1, 0],
                          [1, 0, 0, 1],
                          [1, 0, 1, 0],
                          [1, 1, 0, 1],
                          [1, 1, 1, 0]], dtype=np.float64)

In [3]:
# construct additional dataset by repeating true_table 9 times
add_set = np.tile(true_table, (9, 1))

In [4]:
# replace A,B,C zeros with random values in interval 0,0.4
np.place(add_set[:,:-1], add_set[:,:-1]==0, np.random.uniform(0,0.4,(add_set[:,:-1]==0).sum()))

In [5]:
# replace A,B,C ones with random values in interval 0.6,1.2
np.place(add_set[:,:-1], add_set[:,:-1]==1, np.random.uniform(0.6,1.2,(add_set[:,:-1]==1).sum()))

In [6]:
# create train dataset concatenating initial true_table and generated add_set
dataset = np.concatenate((true_table, add_set), axis=0)

In [7]:
## ver.2
# dataset = np.tile(true_table, (10, 1))

## exclude true table and D
# abc = dataset[true_table.shape[0]:,:-1]

## replace zeros with values in 0,0.4 interval
# abc[abc == 0] = np.random.uniform(0.0, 0.4, (abc == 0).sum())

## replace ones with values in 0.6,1.2 interval
# abc[abc == 1] = np.random.uniform(0.6, 1.2, (abc == 1).sum())

## insert transformed a,b,c in generated data
# dataset[true_table.shape[0]:,:-1] = abc

In [8]:
print("size:\n", dataset.shape)
print("dataset:\n", dataset[:16,:])

size:
 (80, 4)
dataset:
 [[0.         0.         0.         1.        ]
 [0.         0.         1.         0.        ]
 [0.         1.         0.         1.        ]
 [0.         1.         1.         0.        ]
 [1.         0.         0.         1.        ]
 [1.         0.         1.         0.        ]
 [1.         1.         0.         1.        ]
 [1.         1.         1.         0.        ]
 [0.32717918 0.24362669 0.10095127 1.        ]
 [0.00873603 0.03383183 0.6203537  0.        ]
 [0.13673337 0.75152695 0.03830862 1.        ]
 [0.1226615  0.71705221 0.96565158 0.        ]
 [1.03595933 0.01506316 0.21777113 1.        ]
 [1.1375957  0.01873575 1.14505564 0.        ]
 [0.87518941 0.92186108 0.29360014 1.        ]
 [0.68326328 0.81619332 0.92383726 0.        ]]


In [9]:
# input and output for classifier
X = dataset[:,:-1]
y = dataset[:,-1]

In [10]:
# initializing the MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)

In [11]:
# fitting data to the network
clf.fit(X, y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

In [12]:
# generate 10 samples a,b,c for predict
samples = np.concatenate((np.random.uniform(0.,0.4, 15),np.random.uniform(0.6,1.2, 15)))
np.random.shuffle(samples)
samples = samples.reshape((10,3))

In [13]:
print(samples)

[[0.28233139 1.14800983 1.11130135]
 [0.00878544 0.35102151 0.03929389]
 [0.09754434 0.16822993 0.90286841]
 [1.0586404  0.69790208 0.23018372]
 [0.17642688 0.85779704 1.12224927]
 [0.0984656  0.69148157 0.86659084]
 [0.33335413 0.25938193 0.78333533]
 [0.1984824  0.034682   0.30782063]
 [0.69171065 0.02267086 0.84015946]
 [1.14675109 0.60689921 0.88041076]]


In [14]:
clf.predict(samples)

array([0., 1., 0., 1., 0., 0., 0., 1., 0., 0.])