In [1]:
import numpy as np

In [2]:
# Basic Unary ufuncs list excluding sqrt
METHODS_LIST = ['abs','fabs','square','exp','log','log10','log2','log1p','sign','ceil','floor','rint','modf'
             ,'isnan','isfinite','isinf','cos','cosh','sin','sinh','tan','tanh','arccos','arccosh','arcsin'
             ,'arcsinh','arctan','arctanh','logical_not']

In [3]:
class Sliced_2D():
    def __init__(self, input_array, index=None):
        mask = np.zeros(input_array.shape)
        if index is not None:
            mask = mask + 1
            mask[index[0]:index[1],index[2]:index[3]] = 0
        self.arr = np.ma.masked_array(input_array, mask=mask)
    
    def sqrt(self):
    # At locations -where the condition is True, the -out array will be set to the ufunc result.
    # Where the condition is False, the -out array will be set to zero.
        return np.sqrt(np.abs(self.arr).filled(0))
    
    # convert the original 2D array into a 3D one by copying
    def repeat3d(self, repeats=2):
        return np.repeat(self.arr[:, :, np.newaxis], repeats, axis=2)

In [4]:
# Add ufunc methods to class Sliced_2D
for i in METHODS_LIST:
    # define function
    exec(f"def {i}(self):\
         return np.{i}(self.arr.filled(0))")
    
    #  set attribute to class Sliced_2D
    exec(f"setattr(Sliced_2D, '{i}', {i})")
    
    # delete function
    exec(f"del {i}")

In [5]:
# example #1
arr_1 = np.arange(25).reshape(5,5)**2
print(arr_1)

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


In [6]:
# without slice
obj_1 = Sliced_2D(arr_1)

In [7]:
print(obj_1.sqrt())

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


In [8]:
# with slice start_0,stop_0,start_1,stop_1
obj_2 = Sliced_2D(arr_1,[1,4,1,4])

In [9]:
print(obj_2.sqrt())

[[ 0.  0.  0.  0.  0.]
 [ 0.  6.  7.  8.  0.]
 [ 0. 11. 12. 13.  0.]
 [ 0. 16. 17. 18.  0.]
 [ 0.  0.  0.  0.  0.]]


In [10]:
# example #2
np.random.seed(43)
arr_2 = np.random.randn(25).reshape(5,5)
print(arr_2)

[[ 0.25739993 -0.90848143 -0.37850311 -0.5349156   0.85807335]
 [-0.41300998  0.49818858  2.01019925  1.26286154 -0.43921486]
 [-0.34643789  0.45531966 -1.66866271 -0.8620855   0.49291085]
 [-0.1243134   1.93513629 -0.61844265 -1.04683899 -0.88961759]
 [ 0.01404054 -0.16082969  2.23035965 -0.39911572  0.05444456]]


In [11]:
obj_3 = Sliced_2D(arr_2,[2,4,0,3])

In [12]:
print(obj_3.fabs())

[[0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.34643789 0.45531966 1.66866271 0.         0.        ]
 [0.1243134  1.93513629 0.61844265 0.         0.        ]
 [0.         0.         0.         0.         0.        ]]


In [13]:
print(obj_3.floor())

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  0. -2.  0.  0.]
 [-1.  1. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [14]:
# example #3 for convert 2D into 3D
arr_3 = np.arange(9).reshape(3,3)
print(arr_3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
obj = Sliced_2D(arr_3)

In [16]:
d3d = obj.repeat3d(2)

In [17]:
print(d3d[:,:,0])
print(d3d[:,:,1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
